apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  namespace: myapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mydeploy
  template:
    metadata:
      labels:
        app: mydeploy
    spec:
      containers:
        - name: myapp
          image: myimage
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: FOO
              value: bar
