apiVersion: v1
kind: Service
metadata:
  name: another-web-app
  namespace: another-web-app
spec:
  selector:
    app: another-web-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
